---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  ##
  # ^DONE Create service selector labels here
  ##
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress
data:
  host: wordpress-mysql
  user: wordpress
  ##
  # ^DONE create non-sensative data attributes
  ##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  ##
  # ^DONE Create app selector labels here
  ##
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    ##
    # ^DONE Create metadata labels here
    ##
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
          - name: WORDPRESS_DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: wordpress
                key: host
          - name: WORDPRESS_DB_USER
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: user
        ##
        # ^DONE mount non-sensitive environment vars from configmap ref
        # WORDPRESS_DB_HOST | WORDPRESS_DB_USER
        ##
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database
                key: user-password
        ##
        # ^DONE mount sensitive environment vars from secret ref
        # WORDPRESS_DB_PASSWORD (hint use the user-password key)
        ##
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wp-data-volume
          mountPath: /var/www/html
      ##
      # ^DONE define volume mounts here, be sure to reference
      # the PVC in your container spec
      ##
      volumes:
      - name: wp-data-volume
        persistentVolumeClaim:
          claimName: wp-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

